### ISSUE TITLE
Multiple levels of children in _toc.yml?

### ISSUE THREAD

**Issue by leecalcote** [vsoch/docsy-jekyll#3]
Hi,

Does _toc.yml support nested `children:`? e.g.

```
- title: Documentation
  url: '#'
  links:
    - title: Overview
      url: '#'
    - title: Installation
      url: installation
      children:
        - title: Type
          url: installation/type
          children:
          - title: Water
            url: installation/type/water
          - title: Sand
            url: installation/type/sand
          - title: Fire
            url: installation/type/fire
        - title: Organization
          url: installation/organization
    - title: Architecture
      url: architecture
```
