### ISSUE TITLE
White Header Menu with black text

### ISSUE THREAD

**Issue by gregdegruy** [vsoch/docsy-jekyll#39]
I see the default header is a blue color.

![image](https://user-images.githubusercontent.com/8151045/109741935-fa493a00-7b82-11eb-8cad-9272be5bb685.png)

When I set the color in `_config.yml` to `color: "#FFFFFF"` my header becomes this hiding most of the text unless I highlight to reveal it has also been set to white.

![image](https://user-images.githubusercontent.com/8151045/109741961-0503cf00-7b83-11eb-8996-903430735b01.png)

**Comment by vsoch** [comment]
That style attribute isn't exposed in the _config.yml, but you can easily update it your self! In assets/css/main.css you'll want to change:

```css
.navbar-dark .navbar-brand {
    color: #fff;
}
```
and
```css
.navbar-dark .navbar-nav .nav-link {
    color: rgba(255, 255, 255, .75);
}
```
and then add color: black (or similar) to:

```css
.gh-source__repository {
    display: inline-block;
    max-width: 100%;
    margin-left: 1.2rem;
    font-weight: 700;
    text-overflow: ellipsis;
    overflow: hidden;
    vertical-align: middle;
}
```
For all of the above, change "color" to black (or what you want for the text). Generally if there is something on the page that isn't styled correctly, you can right click --> inspect and use the console to select the element of interest and test changing the style. When you find something that works, make a change in the actual file.
