### ISSUE TITLE
 [Feature request] Tag support

### ISSUE THREAD

**Issue by noraj** [vsoch/docsy-jekyll#7]
## Feature idea

Adding tags (keywords) in frontmatter (meta-data) will generate a page referencing all pages containing this page.

Example:

In frontmatter you add (in YAML for example):

```yaml
---
title: My Document
summary: A brief description of my document.
authors:
    - Waylan Limberg
    - Tom Christie
date: 2018-07-10
some_url: https://example.com*
tags:
    - dev
    - python
---
```

So it will create a endpoint http://example.org/tag/#dev and http://example.org/tag/#python referencing, respectively, all pages containing the dev tag and the python tag.

Then on the page of the documentation where there is such a tags frontmatter, the page will contain some tag link #dev and #python respectively referencing the previously mentioned endpoints.

## Related

The feature already exists in Jekyll, there is just to use it in the theme :)

A more heated discussion on why it is useful to have tags on documentation : https://github.com/mkdocs/mkdocs/issues/1828

Similar issue in Jekyll documentation themes:

- https://github.com/pmarsceill/just-the-docs/issues/255

## Example

This feature is already introduced in [Documentation Next](https://jekyll-themes.com/documentation-next/) Jekyll theme.

See https://idratherbewriting.com/documentation-theme-jekyll-next-version/sample1.html
![image](https://user-images.githubusercontent.com/16578570/69835227-3f741300-1240-11ea-83e9-8afff9b74f22.png)
